### ISSUE TITLE
Package manager documentation

### ISSUE THREAD

**Issue by roaldarbol** [BrianPugh/belay#42]
The package manager is already dawning on me. I really really like it! However, I'm a bit confused by:

Belay assumes your project contains a python-package with the same name as tool.belay.name located in the root of your project.

Does that mean you cannot have just a pyproject.toml file, the python script and nothing else in a repo? (except for the autogenerated .belay-lib).

**Comment by BrianPugh** [comment]
correct, you're project should look like:

```
my-repo-name/
    pyproject.toml
    my_project/
        __init__.py
        other_stuff.py
    main.py
```

I've considered making the project folder (`my_project/`) optional, but originally decided against it because:

1. Ideally, for good code organization, the majority of your code should be in `my_project/`, this makes it easier to unit-test either using cpython or on-computer micropython (see [micropython unittest](https://github.com/micropython/micropython-lib/tree/master/python-stdlib/unittest)).

2. With the code being in `my_project`, it's easier to import in belay code instead of doing something odd like `from main import foo`.

3. Making it optional encourages putting a large amount of code in `main.py`, going against point (1).

I'm still open to making it optional (it would be quite easy), would just like to hear your use-case.

Also, fyi, currently the `keep` setting in `device.sync` is not working for folders. Currently, the biggest issue is that a `sync` call will delete the `lib/` folder, which is almost never desired. I should have this fixed within the next 12 hours. I appreciate all the feedback you've been giving, slowly Belay is becoming more robust and generically useful!

Note to self: need to update the docs for the belay CLI in general. In the meantime, run `belay --help`; there might be commands that help your projects.

**Comment by BrianPugh** [comment]
I think for your usecase, I should add a `device.install()` that takes no arguments and installs the cached libraries to device. This should be intended for third party libraries (e.g. [official micropython-lib](https://github.com/micropython/micropython-lib) or [some modules I've been making](https://github.com/BrianPugh/micropython-libs/tree/main/lib)).

Other local modules specific to your project can be "installed" via the `device.sync()` command. The difference between these files and the cached third party libraries is that there's an expectation that you don't locally modify the third-party libraries.

Totally open to other ideas/opinions/thoughts.

**Comment by roaldarbol** [comment]
I think I'm coming from the more applied side, where we need a script in order to run an experiment. The vision is to democratize open, low-cost, hardware. So removing confusing fluff is something I focus on a lot; so it's not a practical limitation, it's more considering UX, how quick will people get confused. And here, say they've written a single short command - now they need an extra folder, `init.py` and `main.py` which they will never actively touch - if you've not built packages before, that's confusing (I've been through that). 

That said, I'm really growing fond of the way Poetry works. Maybe it would be worth leaning on some of their methods, then a way around it could maybe to have a `belay new <folder-name>` command, which generates the minimal proposed folder+file structure. Have prompts that asks about name, etc., and command line output that explains where to put your files.

**Comment by roaldarbol** [comment]
Also, happy that you appreciate the feedback! I really enjoy this part of open source development, and it's the reason I do engage - it's a pleasure working with you! 😃

**Comment by BrianPugh** [comment]
I never really use the `poetry new` command in favor of [my own python template](https://github.com/BrianPugh/python-template), but I certainly understand the appeal of `poetry new`, so I think it would be a good addition. However, it might also introduce confusion; for many projects a `poetry new` (mixed cpython/micropython project) would be more appropriate than a `belay new` (micropython-only project).

More I think about it, the more OK I am with having the project folder be optional. Would you be in favor of "If `tool.belay.name` is not defined, don't attempt that folder sync"?

**Comment by BrianPugh** [comment]
In `Device.sync` for parameter `keep`, folders are now supported and `/lib` is now in the default keep list #44.

**Comment by BrianPugh** [comment]
With #46 the package folder is now optional. I'll add a `belay new` command soon. For a `belay init` command, it's a little more complicated since it has to also be circuitpython compatible. Totally doable, though.

**Comment by roaldarbol** [comment]
@BrianPugh. This speed of user-dev feedback loop, time-to-implementation is insane!😃 Sounds great too re the `new` and `init` methods👍🏼

**Comment by roaldarbol** [comment]
I’ll be gone for the weekend, but I’ll give it a go on Monday. I can also help out with writing some documentation if you need a hand.

**Comment by BrianPugh** [comment]
sounds good! and help is always welcomed!

**Comment by BrianPugh** [comment]
@roaldarbol I've added significant improvements to both the package-manager tool, as well as the documentation. Let me know what you think!

**Comment by roaldarbol** [comment]
Awesome, I'll have a look at it soon!

**Comment by BrianPugh** [comment]
marking this as closed for now; let me know if you have any questions!
