### ISSUE TITLE
WebREPL support?

### ISSUE THREAD

**Issue by roger-** [BrianPugh/belay#8]
Is it possible to use this without a physically connected board (e.g. via the WebREPL)?

**Comment by BrianPugh** [comment]
I haven't explicitly tested, but I'll work on this a little bit today. I'll update you on the results.

**Comment by BrianPugh** [comment]
So i have a basic version working on the `webrepl` branch (see example 09). The performance is kind of lackluster, since I think a lot of the pyboard code from micropython was written under the assumption of a low-latency connection. I'll try and optimize it a bit, but mediocre performance might just be the best we get.

Any feedback would be appreciated!

**Comment by BrianPugh** [comment]
Added support in the newly released `v0.4.0`, we can optimize performance over time, but this should be "good enough" for some projects.
